#!/bin/bash
#
# This shell was write for netroid documentation generate & build,
# use khaleesi(https://github.com/vince-styling/khaleesi) as generator.
#

src_dir=~/dev/netroid/docs
dest_dir=~/dev/netroid/site
line_numbers="true"
css_class="highlight"
time_pattern="%Y-%m-%d %H:%M"
date_pattern="%F"

if [[ "$1" == "generate" ]]; then
  diff=$([ "$2" == 'diff' ] && echo "true" || echo "false")
  khaleesi generate --src-dir "$src_dir" --dest-dir "$dest_dir" --line-numbers $line_numbers --css-class $css_class --time-pattern "$time_pattern" --date-pattern "$date_pattern" --diff-plus $diff

elif [[ "$1" == "serve" ]]; then
  #nohup ruby -run -e httpd $dest_dir -p 9090 &
  ruby -run -e httpd $dest_dir -p 9090

elif [[ "$1" == "build" ]]; then
  temperary_dest_dir=~/tmp_site

  rm -fr $temperary_dest_dir
  mkdir $temperary_dest_dir

  cd $src_dir

  git checkout master

  khaleesi build --src-dir "$src_dir" --dest-dir "$temperary_dest_dir" --line-numbers $line_numbers --css-class $css_class --time-pattern "$time_pattern" --date-pattern "$date_pattern"

  cd ..
  git checkout gh-pages

  rsync -auv $temperary_dest_dir/ .
  rm -fr $temperary_dest_dir

fi